version: "3"


services: 
  
  db:  
    container_name: 'boletim'
    image: mysql 
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    expose:
      - "3306"  
    ports:
      - "3306:3306" 
    environment: 
      - MYSQL_DATABASE=boletim 
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_ROOT_HOST=%
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app: 
    depends_on: 
      db: 
        condition: service_healthy
    build: . 
    command: npm start  
    ports:
      - "5000:5000" 
    volumes:
      - .:/usr/app  

